# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileHW02-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileHW02-iOS
  pod 'Toast-Swift', '~> 2.0.0'

  target 'MobileHW02-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileHW02-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
